docker-compose-yaml: docker-compose.yml
ssh: lagoon-ssh.aenesdemir.net:22
api: https://lagoon-api.aenesdemir.net/graphql
project: wordpress-example

routes:
  autogenerate:
    enabled: false

gke-wordpress:
  environments:
    test:
      routes:
        - varnish:
            - wordpress-demo.aenesdemir.net:
                tls-acme: 'false'
                insecure: Allow
        - nginx:
            - nginx-wordpress-demo.aenesdemir.net:
                tls-acme: 'false'
                insecure: Allow
                annotations:
                  nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
                  nginx.ingress.kubernetes.io/proxy-buffers: 32 16k
                  nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      cronjobs:
      - name: cronjob
        schedule: "H * * * *"
        command: wp cron event run --due-now --path=`/app/web/`
        service: cli

tasks:
  post-rollout:
    - run:
        # TODO: This task is for demo purposes only - Best remove this when you going to use this as production instance
        name: install wordpress if not installed
        command: |
          if ! $(cd web && wp core is-installed); then
            cd web && wp core install --url=$LAGOON_ROUTE --title="amazee.io wordpress-example - $BRANCH" --admin_user=admin --admin_email=admin@example.com --skip-email --allow-root
          fi
        service: cli

# environments:
#   master:
#     cronjobs:
#       - name: cronjob
#         schedule: "H * * * *"
#         command: wp cron event run --due-now --path=`/app/web/`
#         service: cli
     
